### ISSUE TITLE
Adherence to skipTests

### ISSUE THREAD

**Issue by jacobilsoe** [karma-runner/maven-karma-plugin#7]
It would be nice if maven-karma-plugin skipped running tests if the skipTests property was present. I know of the skipKarma property, but it would be useful if the plugin adhered to skipTests as well.

**Comment by synergiator** [comment]
Hi - since 2013 that Maven Failsaife Plugin url has moved to http://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html

@kelveden - how to use properly "_skipKarma_" from Maven command line?

Not working e.g.
mvn clean install -DskipKarma=true
mvn clean install -Dmaven.skipKarma=true

**Comment by shravank28** [comment]
Try this:
mvn clean install -Dskip.karma=true
